import os
import sys
import psycopg2
import pymysql
from dotenv import load_dotenv

sys.stdout.reconfigure(encoding='utf-8')

BACKEND_DIR = r"C:\Users\Anrid\plomaap_react_estable\backend_flask"
load_dotenv(os.path.join(BACKEND_DIR, ".env"), override=True)
pg_pass = os.getenv("POSTGRES_PASSWORD", "")

print("=" * 65)
print("PARTE B - PASO B1: EJECUCIÓN DEL DDL APROBADO EN DOCKER (PUERTO 5434)")
print("=" * 65)

conn = psycopg2.connect(
    host="localhost",
    port=5434,
    user="postgres",
    password=pg_pass,
    dbname="plomapp"
)
conn.autocommit = False

try:
    with conn.cursor() as cur:
        # B1. Execute exact approved DDL
        print("[*] Creando las 7 tablas de Hogar Digital e índices en public...")
        cur.execute("""
        -- ============================================================================
        -- 1. CATÁLOGOS DE REFERENCIA
        -- ============================================================================
        CREATE TABLE IF NOT EXISTS public.room_type_catalog (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(50) NOT NULL UNIQUE,
            name VARCHAR(100) NOT NULL,
            description TEXT,
            icon VARCHAR(50),
            display_order INTEGER DEFAULT 0 NOT NULL,
            is_active BOOLEAN DEFAULT TRUE NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS public.asset_type_catalog (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(50) NOT NULL UNIQUE,
            name VARCHAR(100) NOT NULL,
            category VARCHAR(50) NOT NULL,
            icon VARCHAR(50),
            default_maintenance_months INTEGER,
            display_order INTEGER DEFAULT 0 NOT NULL,
            is_active BOOLEAN DEFAULT TRUE NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        -- ============================================================================
        -- 2. ENTIDADES DE HOGAR DIGITAL
        -- ============================================================================
        CREATE TABLE IF NOT EXISTS public.homes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            owner_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            name VARCHAR(120) NOT NULL,
            type VARCHAR(30) NOT NULL DEFAULT 'apartment' CHECK (type IN ('apartment', 'house', 'studio', 'office', 'other')),
            approximate_area NUMERIC(8, 2),
            rooms_count INTEGER DEFAULT 0 NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_homes_owner ON public.homes(owner_id);

        CREATE TABLE IF NOT EXISTS public.home_members (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            home_id INTEGER NOT NULL REFERENCES public.homes(id) ON DELETE CASCADE,
            user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            role VARCHAR(30) NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member', 'guest')),
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_home_member UNIQUE (home_id, user_id)
        );
        CREATE INDEX IF NOT EXISTS idx_home_members_home ON public.home_members(home_id);
        CREATE INDEX IF NOT EXISTS idx_home_members_user ON public.home_members(user_id);

        CREATE TABLE IF NOT EXISTS public.saved_locations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            home_id INTEGER REFERENCES public.homes(id) ON DELETE SET NULL,
            label VARCHAR(100) NOT NULL,
            address VARCHAR(255) NOT NULL,
            latitude NUMERIC(10, 8),
            longitude NUMERIC(11, 8),
            place_id VARCHAR(255),
            reference VARCHAR(255),
            is_default BOOLEAN DEFAULT FALSE NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_saved_locations_user ON public.saved_locations(user_id);
        CREATE INDEX IF NOT EXISTS idx_saved_locations_home ON public.saved_locations(home_id);

        CREATE TABLE IF NOT EXISTS public.home_rooms (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            home_id INTEGER NOT NULL REFERENCES public.homes(id) ON DELETE CASCADE,
            name VARCHAR(100) NOT NULL,
            type VARCHAR(50) NOT NULL REFERENCES public.room_type_catalog(code) ON DELETE RESTRICT ON UPDATE CASCADE,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_home_rooms_home ON public.home_rooms(home_id);
        CREATE INDEX IF NOT EXISTS idx_home_rooms_type ON public.home_rooms(type);

        CREATE TABLE IF NOT EXISTS public.home_assets (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            home_id INTEGER NOT NULL REFERENCES public.homes(id) ON DELETE CASCADE,
            room_id INTEGER REFERENCES public.home_rooms(id) ON DELETE SET NULL,
            asset_type VARCHAR(50) NOT NULL REFERENCES public.asset_type_catalog(code) ON DELETE RESTRICT ON UPDATE CASCADE,
            brand VARCHAR(100),
            model VARCHAR(100),
            installation_date DATE,
            last_maintenance DATE,
            warranty_until DATE,
            metadata JSONB DEFAULT '{}'::jsonb,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_home_assets_home ON public.home_assets(home_id);
        CREATE INDEX IF NOT EXISTS idx_home_assets_room ON public.home_assets(room_id);
        CREATE INDEX IF NOT EXISTS idx_home_assets_type ON public.home_assets(asset_type);
        CREATE INDEX IF NOT EXISTS idx_home_assets_metadata ON public.home_assets USING gin (metadata);
        """)
        print("[OK] Paso B1 completado: DDL ejecutado exitosamente.")

        # B2. Insert Catalog Seeds
        print("\n" + "=" * 65)
        print("PARTE B - PASO B2: INSERCIÓN DE SEEDS DE CATÁLOGO")
        print("=" * 65)

        # 1. room_type_catalog (7 rows)
        room_seeds = [
            ("cocina", "Cocina", "Espacio para preparación de alimentos", "kitchen", 1),
            ("bano", "Baño", "Servicios sanitarios y duchas", "bath", 2),
            ("sala", "Sala", "Área social y de estar", "couch", 3),
            ("habitacion", "Habitación", "Dormitorio principal o secundario", "bed", 4),
            ("patio", "Patio", "Área exterior o patio interior", "tree", 5),
            ("balcon", "Balcón", "Terraza o balcón exterior", "sun", 6),
            ("zona_lavado", "Zona de lavado", "Lavandería y secado", "shirt", 7),
        ]

        cur.executemany("""
        INSERT INTO public.room_type_catalog (code, name, description, icon, display_order, is_active)
        VALUES (%s, %s, %s, %s, %s, TRUE)
        ON CONFLICT (code) DO UPDATE
        SET name = EXCLUDED.name, description = EXCLUDED.description, icon = EXCLUDED.icon, display_order = EXCLUDED.display_order;
        """, room_seeds)
        print(f"[OK] Inserción en room_type_catalog: {len(room_seeds)} filas.")

        # 2. asset_type_catalog (8 rows)
        asset_seeds = [
            ("calentador", "Calentador de agua", "gas_plomeria", "water-boiler", 12, 1),
            ("lavadora", "Lavadora", "electrodomesticos", "washing-machine", 12, 2),
            ("ducha", "Ducha / Grifería", "plomeria", "shower", 6, 3),
            ("lavamanos", "Lavamanos", "plomeria", "sink", 6, 4),
            ("sanitario", "Sanitario", "plomeria", "toilet", 6, 5),
            ("iluminacion", "Iluminación", "electricidad", "lightbulb", 24, 6),
            ("enchufe", "Tomacorriente / Enchufe", "electricidad", "plug", 24, 7),
            ("aire_acondicionado", "Aire acondicionado", "climatizacion", "fan", 6, 8),
        ]

        cur.executemany("""
        INSERT INTO public.asset_type_catalog (code, name, category, icon, default_maintenance_months, display_order, is_active)
        VALUES (%s, %s, %s, %s, %s, %s, TRUE)
        ON CONFLICT (code) DO UPDATE
        SET name = EXCLUDED.name, category = EXCLUDED.category, icon = EXCLUDED.icon,
            default_maintenance_months = EXCLUDED.default_maintenance_months, display_order = EXCLUDED.display_order;
        """, asset_seeds)
        print(f"[OK] Inserción en asset_type_catalog: {len(asset_seeds)} filas.")

    conn.commit()
    print("[OK] Transacción confirmada exitosamente.")

except Exception as e:
    conn.rollback()
    print(f"[!] ERROR en Paso B1/B2: {e}")
    conn.close()
    sys.exit(1)

conn.close()

# B3. Final Integrity Verification
print("\n" + "=" * 65)
print("PARTE B - PASO B3: VERIFICACIÓN FINAL DE INTEGRIDAD")
print("=" * 65)

# Connect to Docker (5434)
conn_doc = psycopg2.connect(host="localhost", port=5434, user="postgres", password=pg_pass, dbname="plomapp")
with conn_doc.cursor() as cur:
    print("[1] Conteos de tablas existentes en Docker (5434):")
    baseline = {
        "users": 14,
        "services": 4,
        "appointments": 10,
        "user_addresses": 6,
        "user_favorites": 2,
        "technician_profiles": 2,
        "devices": 0,
        "webauthn_credentials": 0
    }
    all_baseline_ok = True
    for t, exp in baseline.items():
        cur.execute(f"SELECT COUNT(*) FROM public.{t};")
        cnt = cur.fetchone()[0]
        match = (cnt == exp)
        if not match:
            all_baseline_ok = False
        print(f"    - public.{t:<22}: {cnt:2d} (esperado: {exp:2d}) -> {'OK' if match else 'ERROR'}")
    assert all_baseline_ok, "ERROR: La línea base de tablas existentes fue alterada."

    print("\n[2] Estado de las 7 tablas nuevas de Hogar Digital:")
    new_expected = {
        "room_type_catalog": 7,
        "asset_type_catalog": 8,
        "homes": 0,
        "home_members": 0,
        "saved_locations": 0,
        "home_rooms": 0,
        "home_assets": 0
    }
    all_new_ok = True
    for t, exp in new_expected.items():
        cur.execute(f"SELECT COUNT(*) FROM public.{t};")
        cnt = cur.fetchone()[0]
        match = (cnt == exp)
        if not match:
            all_new_ok = False
        print(f"    - public.{t:<22}: {cnt:2d} (esperado: {exp:2d}) -> {'OK' if match else 'ERROR'}")
    assert all_new_ok, "ERROR: Discrepancia en conteos de tablas nuevas."

conn_doc.close()

# Connect to Native PG (5432) to verify it is intact
conn_nat = psycopg2.connect(host="localhost", port=5432, user="postgres", password=pg_pass, dbname="plomapp")
with conn_nat.cursor() as cur:
    cur.execute("SELECT COUNT(*) FROM public.users;")
    nat_users = cur.fetchone()[0]
    print(f"\n[3] PostgreSQL Nativo (puerto 5432): Activo, {nat_users} usuarios (INTACTO).")
conn_nat.close()

# Connect to MySQL (3306) to verify it is untouched
conn_my = pymysql.connect(
    host=os.getenv("MYSQL_HOST", "localhost"),
    user=os.getenv("MYSQL_USER", "root"),
    password=os.getenv("MYSQL_PASSWORD", ""),
    port=int(os.getenv("MYSQL_PORT", 3306)),
    database=os.getenv("MYSQL_DB", "plomapp")
)
with conn_my.cursor() as cur:
    cur.execute("SHOW TABLES;")
    my_tables = cur.fetchall()
    total_my = 0
    for t in my_tables:
        cur.execute(f"SELECT COUNT(*) FROM `{t[0]}`;")
        total_my += cur.fetchone()[0]
    print(f"\n[4] MySQL (puerto 3306): {len(my_tables)} tablas, {total_my} registros (100% INTACTO).")
    assert len(my_tables) == 19 and total_my == 139, "ERROR: MySQL fue alterado."
conn_my.close()

print("\n" + "=" * 65)
print("TODAS LAS VERIFICACIONES DE LA PARTE B PASARON AL 100%")
print("=" * 65)
