import os
import sys
import psycopg2
from dotenv import load_dotenv

sys.stdout.reconfigure(encoding='utf-8')

BACKEND_DIR = r"C:\Users\Anrid\plomaap_react_estable\backend_flask"
load_dotenv(os.path.join(BACKEND_DIR, ".env"), override=True)
pw = os.getenv("POSTGRES_PASSWORD", "")

print("=" * 65)
print("FASE 7 - PASO 2: CREACIÓN DE LA TABLA profile_attributes")
print("=" * 65)

ddl = """
CREATE TABLE IF NOT EXISTS public.profile_attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(30) NOT NULL,
    entity_id INTEGER NOT NULL,
    attribute_key VARCHAR(100) NOT NULL,
    attribute_value JSONB NOT NULL,
    source VARCHAR(30) NOT NULL CHECK (source IN (
        'onboarding', 'explicit_user_input', 'search', 'booking',
        'rating', 'home_asset', 'inferred', 'system'
    )),
    confidence NUMERIC(4,3) NOT NULL DEFAULT 1.000 CHECK (confidence >= 0 AND confidence <= 1),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_profile_attribute UNIQUE (entity_type, entity_id, attribute_key)
);
CREATE INDEX IF NOT EXISTS idx_profile_attributes_entity ON public.profile_attributes(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_profile_attributes_source ON public.profile_attributes(source);
"""

conn = psycopg2.connect(host="localhost", port=5434, user="postgres", password=pw, dbname="plomapp")
conn.autocommit = False

try:
    with conn.cursor() as cur:
        cur.execute(ddl)
    conn.commit()
    print("[OK] Tabla e índices de profile_attributes creados exitosamente.")
except Exception as e:
    conn.rollback()
    print(f"[!] Error creando tabla: {e}")
    conn.close()
    sys.exit(1)

with conn.cursor() as cur:
    cur.execute("""
    SELECT column_name, data_type, is_nullable 
    FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'profile_attributes'
    ORDER BY ordinal_position;
    """)
    cols = cur.fetchall()
    print(f"\nEstructura de public.profile_attributes ({len(cols)} columnas):")
    for c in cols:
        print(f"  - {c[0]:<25} {c[1]:<20} NULLABLE={c[2]}")

    cur.execute("""
    SELECT indexname, indexdef 
    FROM pg_indexes 
    WHERE schemaname = 'public' AND tablename = 'profile_attributes';
    """)
    indexes = cur.fetchall()
    print(f"\nÍndices ({len(indexes)}):")
    for idx in indexes:
        print(f"  - {idx[0]}")

conn.close()
print("\n" + "=" * 65)
print("PASO 2 COMPLETADO CON ÉXITO")
print("=" * 65)
