import os
import sys
import psycopg2
from dotenv import load_dotenv

sys.stdout.reconfigure(encoding='utf-8')

BACKEND_DIR = r"C:\Users\Anrid\plomaap_react_estable\backend_flask"
load_dotenv(os.path.join(BACKEND_DIR, ".env"), override=True)
pw = os.getenv("POSTGRES_PASSWORD", "")

print("=" * 65)
print("PARTE B - PASO B1 & B2: CREACIÓN DE TABLAS DE EVENT TRACKING EN DOCKER (5434)")
print("=" * 65)

conn = psycopg2.connect(host="localhost", port=5434, user="postgres", password=pw, dbname="plomapp")
conn.autocommit = False

ddl = """
-- ============================================================================
-- FASE 6: EVENT TRACKING
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.app_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
    session_id VARCHAR(100),
    event_type VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50),
    entity_id INTEGER,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_app_events_user ON public.app_events(user_id);
CREATE INDEX IF NOT EXISTS idx_app_events_type ON public.app_events(event_type);
CREATE INDEX IF NOT EXISTS idx_app_events_entity ON public.app_events(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_app_events_created ON public.app_events(created_at);

CREATE TABLE IF NOT EXISTS public.recommendation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    recommendation_type VARCHAR(50) NOT NULL,
    entity_id INTEGER NOT NULL,
    score NUMERIC(6, 4),
    algorithm_version VARCHAR(30) NOT NULL,
    position INTEGER,
    shown_at TIMESTAMP WITHOUT TIME ZONE,
    clicked_at TIMESTAMP WITHOUT TIME ZONE,
    converted_at TIMESTAMP WITHOUT TIME ZONE,
    metadata JSONB DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_recommendation_events_user ON public.recommendation_events(user_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_events_type ON public.recommendation_events(recommendation_type);
"""

try:
    with conn.cursor() as cur:
        print("[*] Ejecutando DDL aprobado para app_events y recommendation_events...")
        cur.execute(ddl)
    conn.commit()
    print("[OK] Tablas e índices creados exitosamente.")
except Exception as e:
    conn.rollback()
    print(f"[!] Error ejecutando DDL: {e}")
    conn.close()
    sys.exit(1)

# Verify table creation and structure
with conn.cursor() as cur:
    for tbl in ['app_events', 'recommendation_events']:
        cur.execute(f"SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '{tbl}' ORDER BY ordinal_position;")
        cols = cur.fetchall()
        print(f"\nEstructura de public.{tbl} ({len(cols)} columnas):")
        for col in cols:
            print(f"  - {col[0]:<25} {col[1]:<20} NULLABLE={col[2]}")

    cur.execute("""
    SELECT tablename, indexname, indexdef 
    FROM pg_indexes 
    WHERE schemaname = 'public' AND tablename IN ('app_events', 'recommendation_events')
    ORDER BY tablename, indexname;
    """)
    indexes = cur.fetchall()
    print(f"\nÍndices creados ({len(indexes)}):")
    for idx in indexes:
        print(f"  - {idx[0]}.{idx[1]}")

conn.close()
print("\n" + "=" * 65)
print("PASO B1 Y B2 COMPLETADOS CON ÉXITO")
print("=" * 65)
