import os
import sys
import psycopg2
from dotenv import load_dotenv

sys.stdout.reconfigure(encoding='utf-8')

BACKEND_DIR = r"C:\Users\Anrid\plomaap_react_estable\backend_flask"
load_dotenv(os.path.join(BACKEND_DIR, ".env"))
pg_pass = os.getenv("POSTGRES_PASSWORD", "")

print("=" * 65)
print("PASO 7: PRUEBA CONTROLADA DE PGVECTOR EN CONTENEDOR (PUERTO 5434)")
print("=" * 65)

conn = psycopg2.connect(
    host="localhost",
    port=5434,
    user="postgres",
    password=pg_pass,
    dbname="plomapp"
)
conn.autocommit = False

try:
    with conn.cursor() as cur:
        # 1. Create isolated embeddings table
        print("[1] Creando tabla aislada public.entity_embeddings...")
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.entity_embeddings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type VARCHAR(50) NOT NULL,
            entity_id INTEGER NOT NULL,
            content_text TEXT NOT NULL,
            embedding vector(3),
            model_name VARCHAR(100) NOT NULL,
            dimension INTEGER NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_entity_embedding UNIQUE (entity_type, entity_id, model_name)
        );
        CREATE INDEX IF NOT EXISTS idx_entity_embeddings_lookup ON public.entity_embeddings(entity_type, entity_id);
        CREATE INDEX IF NOT EXISTS idx_entity_embeddings_vector ON public.entity_embeddings USING hnsw (embedding vector_cosine_ops);
        """)
        print("    [OK] Tabla e índice HNSW creados exitosamente.")

        # 2. Insert synthetic embeddings for the 4 real services
        print("\n[2] Insertando embeddings sintéticos de prueba para los 4 servicios reales...")
        synthetic_data = [
            ("service", 1, "Fugas de agua - Goteras, tuberías, llaves", "[0.90, 0.10, 0.10]", "synthetic-test-3d", 3),
            ("service", 2, "Destapes - Baños, cocinas, cañerías", "[0.10, 0.90, 0.10]", "synthetic-test-3d", 3),
            ("service", 3, "Duchas y baños - Grifería, sanitarios, mamparas", "[0.60, 0.60, 0.10]", "synthetic-test-3d", 3),
            ("service", 4, "Instalaciones - Lavaplatos, calentadores, tubería", "[0.10, 0.20, 0.90]", "synthetic-test-3d", 3),
        ]

        for item in synthetic_data:
            cur.execute("""
            INSERT INTO public.entity_embeddings (entity_type, entity_id, content_text, embedding, model_name, dimension)
            VALUES (%s, %s, %s, %s::vector, %s, %s)
            ON CONFLICT (entity_type, entity_id, model_name) DO UPDATE
            SET embedding = EXCLUDED.embedding, content_text = EXCLUDED.content_text;
            """, item)
        print(f"    [OK] {len(synthetic_data)} embeddings sintéticos insertados.")

        # 3. Vector Similarity Search
        print("\n[3] Ejecutando búsqueda por similitud de coseno...")
        print("    Vector de consulta (búsqueda de fuga de agua): [0.85, 0.15, 0.05]")
        query_vector = "[0.85, 0.15, 0.05]"

        cur.execute("""
        SELECT
            e.entity_id,
            s.name,
            s.base_price,
            e.content_text,
            ROUND((e.embedding <=> %s::vector)::numeric, 4) AS distancia_coseno,
            ROUND((1 - (e.embedding <=> %s::vector))::numeric, 4) AS score_similitud
        FROM public.entity_embeddings e
        JOIN public.services s ON e.entity_id = s.id
        WHERE e.entity_type = 'service'
        ORDER BY e.embedding <=> %s::vector ASC;
        """, (query_vector, query_vector, query_vector))

        rows = cur.fetchall()
        print("\n    Resultados ordenados por proximidad semántica (menor distancia / mayor similitud):")
        for rank, r in enumerate(rows, 1):
            print(f"    {rank}. Servicio ID {r[0]}: {r[1]:<20} | Distancia: {r[4]} | Similitud: {r[5]} | Precio: ${r[2]}")

        # Top 1 must be Service 1 (Fugas de agua)
        top_service_id = rows[0][0]
        top_service_name = rows[0][1]
        print(f"\n    Top 1 recuperado: '{top_service_name}' (ID: {top_service_id})")
        assert top_service_id == 1, f"Error en búsqueda vectorial: esperado ID 1, obtenido {top_service_id}"
        print("    [OK] La infraestructura matemática de pgvector operó con 100% de exactitud.")

        # 4. Clean up temporary test embeddings
        print("\n[4] Eliminando datos sintéticos de prueba...")
        cur.execute("DELETE FROM public.entity_embeddings WHERE model_name = 'synthetic-test-3d';")
        cur.execute("SELECT COUNT(*) FROM public.entity_embeddings;")
        final_emb_cnt = cur.fetchone()[0]
        print(f"    [OK] Registros temporales eliminados. Total en entity_embeddings: {final_emb_cnt}")

    conn.commit()
    print("\n" + "=" * 65)
    print("PRUEBA CONTROLADA DE PGVECTOR FINALIZADA EXITOSAMENTE")
    print("=" * 65)

except Exception as e:
    conn.rollback()
    print(f"ERROR durante la prueba de pgvector: {e}")
    sys.exit(1)
finally:
    conn.close()
