import os

BACKEND_DIR = r"C:\Users\Anrid\plomaap_react_estable\backend_flask"
MIGRATION_DIR = os.path.join(BACKEND_DIR, "database_migration")
PLAN_FILE = os.path.join(MIGRATION_DIR, "MIGRATION_PLAN.md")

plan_content = """# 📋 Plan de Migración Oficial: MySQL 8.0 ➔ PostgreSQL 17 (PlomApp)

## 📌 Metadatos del Documento
- **Proyecto:** PlomApp Backend (Flask + SQLAlchemy)
- **Base de Datos Origen:** MySQL 8.0 (`localhost:3306/plomapp`)
- **Base de Datos Destino:** PostgreSQL 17.5 (`localhost:5432/plomapp`)
- **Fecha de Auditoría:** Septiembre 2026
- **Estado de Ejecución:** Fase de Planificación y Preparación (Sin cambios destructivos ejecutados)
- **Política de Seguridad:** Respaldo previo completado, cero pérdida de datos, operaciones 100% reversibles.

---

## 1. Esquema Actual MySQL

Se detectaron **19 tablas** en MySQL con un total de **139 registros** distribuidos en dos capas lógicas:

### A. Capa Moderna PlomApp (Modelos Activos SQLAlchemy)
Mapeadas directamente en `app/database/models.py`:
1. `users` (14 filas) — Usuarios de la plataforma (clientes, técnicos, administradores).
2. `technician_profiles` (2 filas) — Perfiles extendidos de técnicos (especialidades, rating, horarios).
3. `services` (4 filas) — Catálogo base de servicios (Fugas, Destapes, Duchas/baños, Instalaciones).
4. `user_addresses` (6 filas) — Libreta de direcciones guardadas por los usuarios con geolocalización.
5. `user_favorites` (2 filas) — Relación muchos a muchos de servicios favoritos por usuario.
6. `appointments` (10 filas) — Citas y reservas coordinadas entre clientes, técnicos y servicios.
7. `devices` (0 filas) — Registro y rastreo de dispositivos/sesiones activas.
8. `webauthn_credentials` (0 filas) — Credenciales de biometría/Passkeys WebAuthn.

### B. Capa Histórica / Prototipo Anterior (Tablas en Español)
Tablas preservadas del prototipo inicial del sistema:
- `usuarios` (16 filas)
- `perfiles` (15 filas)
- `solicitudes_servicio` (10 filas)
- `cotizaciones` (10 filas)
- `diagnosticos` (10 filas)
- `garantias` (10 filas)
- `pagos` (10 filas)
- `registros_chat` (10 filas)
- `resenas` (10 filas)
- `agendar_servicio` (0 filas)
- `materiales_cotizacion` (0 filas)

---

## 2. Esquema Objetivo PostgreSQL 17

El esquema objetivo en PostgreSQL aprovechará las capacidades modernas de PostgreSQL 17:
- **Identificadores y Secuencias:** Uso de `GENERATED BY DEFAULT AS IDENTITY` para compatibilidad nativa SQL estándar.
- **Tipos Semi-estructurados:** Uso de `JSONB` en lugar de `JSON` plano para indexación rápida con operadores GIN (`@>`, `?`, `?|`).
- **Enums e Integridad:** Columnas `VARCHAR` con `CHECK` constraints o tipos `ENUM` administrados consistentemente por SQLAlchemy.
- **Booleanos Nativos:** `BOOLEAN` nativo en lugar del `TINYINT(1)` de MySQL.
- **Alineación con pgvector:** Preparación para añadir la columna `embedding vector(1536)` (o 768) en tablas `services` y `technician_profiles` una vez habilitada la extensión en la fase correspondiente.

---

## 3. Tabla de Equivalencias de Tipos de Datos

| Tipo en MySQL 8.0 | Tipo en PostgreSQL 17 | Transformación Requerida |
| :--- | :--- | :--- |
| `INT AUTO_INCREMENT` | `INTEGER GENERATED BY DEFAULT AS IDENTITY` | La secuencia debe sincronizarse al ID máximo tras migrar datos |
| `VARCHAR(n)` | `VARCHAR(n)` | Directa (verificar collation UTF-8) |
| `TEXT` | `TEXT` | Directa |
| `TINYINT(1)` | `BOOLEAN` | `0 -> FALSE`, `1 -> TRUE` |
| `DATETIME` | `TIMESTAMP WITHOUT TIME ZONE` | Conversión directa a ISO 8601 |
| `TIMESTAMP` | `TIMESTAMP WITH TIME ZONE` o `TIMESTAMP` | Conservación del timestamp en UTC |
| `DECIMAL(10, 2)` | `NUMERIC(10, 2)` | Directa (precisión monetaria exacta) |
| `DECIMAL(10, 8)` | `NUMERIC(10, 8)` | Coordenadas de latitud |
| `DECIMAL(11, 8)` | `NUMERIC(11, 8)` | Coordenadas de longitud |
| `JSON` | `JSONB` | Parseo a objeto/array nativo binario |
| `ENUM(...)` | `VARCHAR + CHECK` o `CREATE TYPE` | Definición de constraints consistentes en SQLAlchemy |

---

## 4. Tablas que Necesitan Migración

### Prioridad 1: Tablas Core Activas
| Tabla | Registros | Clave Primaria | Dependencias (FK) |
| :--- | :--- | :--- | :--- |
| `services` | 4 | `id` | Ninguna |
| `users` | 14 | `id` | Ninguna |
| `technician_profiles` | 2 | `id` | `users(id)` |
| `user_addresses` | 6 | `id` | `users(id)` |
| `user_favorites` | 2 | `id` | `users(id)`, `services(id)` |
| `appointments` | 10 | `id` | `users(id)`, `services(id)`, `user_addresses(id)` |
| `devices` | 0 | `id` | `users(id)` |
| `webauthn_credentials`| 0 | `id` | `users(id)` |

### Prioridad 2: Tablas Legacy (Preservación)
Se migrarán al esquema `legacy` o con prefijo para asegurar retención histórica sin interferir con las consultas del nuevo backend:
`usuarios`, `perfiles`, `solicitudes_servicio`, `cotizaciones`, `diagnosticos`, `garantias`, `pagos`, `registros_chat`, `resenas`.

---

## 5. Relaciones (Foreign Keys y Restricciones)

```mermaid
erDiagram
    users ||--o| technician_profiles : "1 a 1 (user_id)"
    users ||--o{ user_addresses : "1 a N (user_id CASCADE)"
    users ||--o{ user_favorites : "1 a N (user_id CASCADE)"
    services ||--o{ user_favorites : "1 a N (service_id CASCADE)"
    users ||--o{ appointments : "cliente (user_id)"
    users ||--o{ appointments : "tecnico (technician_id)"
    services ||--o{ appointments : "servicio (service_id)"
    user_addresses ||--o{ appointments : "direccion (user_address_id)"
    users ||--o{ devices : "1 a N (user_id CASCADE)"
    users ||--o{ webauthn_credentials : "1 a N (user_id CASCADE)"
```

- **`technician_profiles`:** `user_id` FK a `users.id` con `UNIQUE` y `ON DELETE CASCADE`.
- **`user_addresses`:** `user_id` FK a `users.id` con `ON DELETE CASCADE`.
- **`user_favorites`:** `user_id` FK a `users.id` con `ON DELETE CASCADE`, `service_id` FK a `services.id` con `ON DELETE CASCADE`.
- **`appointments`:** `user_id` FK a `users.id`, `technician_id` FK a `users.id` (nullable), `service_id` FK a `services.id`, `user_address_id` FK a `user_addresses.id` (nullable).
- **`devices`:** `user_id` FK a `users.id` con `ON DELETE CASCADE`.
- **`webauthn_credentials`:** `user_id` FK a `users.id` con `ON DELETE CASCADE`.

---

## 6. Índices Requeridos en PostgreSQL

1. **`users`:**
   - `CREATE UNIQUE INDEX idx_users_email ON users(email);`
2. **`technician_profiles`:**
   - `CREATE UNIQUE INDEX idx_tech_user_id ON technician_profiles(user_id);`
   - Futuro: `CREATE INDEX idx_tech_specialties_gin ON technician_profiles USING gin (specialties);`
3. **`user_addresses`:**
   - `CREATE INDEX idx_user_addresses_user ON user_addresses(user_id);`
4. **`user_favorites`:**
   - `CREATE UNIQUE INDEX uq_user_service ON user_favorites(user_id, service_id);`
   - `CREATE INDEX idx_user_favorites_user ON user_favorites(user_id);`
5. **`appointments`:**
   - `CREATE INDEX idx_user_date ON appointments(user_id, date);`
   - `CREATE INDEX idx_technician_date ON appointments(technician_id, date);`
   - `CREATE INDEX idx_appointments_service ON appointments(service_id);`
6. **`webauthn_credentials`:**
   - `CREATE UNIQUE INDEX idx_webauthn_cred_id ON webauthn_credentials(credential_id);`
   - `CREATE INDEX idx_webauthn_user ON webauthn_credentials(user_id);`

---

## 7. Datos que Requieren Transformación

1. **Campos Booleanos:**
   - En MySQL son `TINYINT(1)` (`1` / `0`).
   - Transformar a `TRUE` / `FALSE` en PostgreSQL para:
     - `users.email_verified`
     - `technician_profiles.available`
     - `user_addresses.is_default`
2. **Campos JSON:**
   - `technician_profiles.specialties`: Cadena JSON `["plumbing", "drain"]` convertida a estructura `JSONB`.
   - `technician_profiles.schedule`: Cadena JSON con horarios convertida a `JSONB`.
   - `webauthn_credentials.transports`: Cadena JSON convertida a `JSONB`.
3. **Campos de Fecha y Hora:**
   - `appointments.time`: Es `VARCHAR(5)` formato `HH:MM`. Se mantiene como texto o se normaliza a `TIME`.
   - `created_at` / `updated_at`: Conversión a timestamps ISO UTC consistentes.
4. **Actualización de Secuencias Identity:**
   - Para cada tabla con IDs preexistentes, debe ejecutarse:
     ```sql
     SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
     SELECT setval(pg_get_serial_sequence('services', 'id'), COALESCE((SELECT MAX(id) FROM services), 1));
     SELECT setval(pg_get_serial_sequence('appointments', 'id'), COALESCE((SELECT MAX(id) FROM appointments), 1));
     SELECT setval(pg_get_serial_sequence('user_addresses', 'id'), COALESCE((SELECT MAX(id) FROM user_addresses), 1));
     SELECT setval(pg_get_serial_sequence('user_favorites', 'id'), COALESCE((SELECT MAX(id) FROM user_favorites), 1));
     SELECT setval(pg_get_serial_sequence('technician_profiles', 'id'), COALESCE((SELECT MAX(id) FROM technician_profiles), 1));
     ```

---

## 8. Análisis de Riesgos y Mitigaciones

| Riesgo Identificado | Severidad | Mitigación Implementada |
| :--- | :--- | :--- |
| Pérdida accidental de datos en MySQL | Crítica | Regla estricta: operaciones de sólo lectura sobre MySQL. Backup dual (SQL + JSON) completado con SHA-256. |
| Inconsistencia de contraseñas de usuarios | Alta | Las contraseñas en `users.password_hash` están hasheadas con `bcrypt`. El algoritmo de validación en Flask (`bcrypt.checkpw`) es idéntico e independiente del motor de base de datos. Se transfieren intactas. |
| Violación de Foreign Keys al insertar | Alta | Se establece un orden topológico estricto de migración (padres antes que hijos) y desactivación temporal de triggers si fuera necesario. |
| Desfase de secuencias de auto-incremento | Media | Ejecución garantizada de comandos `setval()` post-migración para que nuevos registros no fallen por conflicto de clave primaria. |
| Incompatibilidad de driver Python | Media | Requiere instalar `psycopg2-binary` en el venv antes de apuntar la conexión. |
| Falla en tiempo de ejecución en producción | Alta | `DATABASE_URL` no se modificará hasta que el entorno PostgreSQL esté 100% probado y validado con tests de integración. |

---

## 9. Orden Recomendado de Migración

```mermaid
flowchart TD
    A[1. Validar Conexión y Credenciales en PostgreSQL] --> B[2. Crear Base de Datos plomapp en PostgreSQL 17]
    B --> C[3. Instalar psycopg2-binary en backend_flask venv]
    C --> D[4. Generar DDL en PostgreSQL vía SQLAlchemy db.create_all]
    D --> E[5. Cargar Datos en Orden Topológico]
    
    subgraph Orden_Topologico [Orden de Carga de Datos]
        E1[services] --> E2[users]
        E2 --> E3[technician_profiles]
        E2 --> E4[user_addresses]
        E2 & E1 --> E5[user_favorites]
        E2 & E1 & E4 --> E6[appointments]
        E2 --> E7[devices]
        E2 --> E8[webauthn_credentials]
    end
    
    E --> Orden_Topologico
    Orden_Topologico --> F[6. Sincronizar Secuencias Identity setval]
    F --> G[7. Validación Cruzada de Conteos e Integridad]
    G --> H[8. Switch Reversible de DATABASE_URL solo tras Aprobación]
```

---

## 10. Procedimiento de Rollback

Si durante o después de la migración se detecta cualquier anomalía:

1. **Reversión Instantánea de Conexión:**
   - La base de datos MySQL original nunca es borrada ni modificada.
   - En `backend_flask/.env`, simplemente se mantiene o restablece la configuración apuntando a MySQL:
     ```env
     # Si DATABASE_URL llegó a definirse, se comenta o elimina:
     # DATABASE_URL=postgresql+psycopg2://usuario:password@localhost:5432/plomapp
     MYSQL_USER=root
     MYSQL_HOST=localhost
     MYSQL_PORT=3306
     MYSQL_DB=plomapp
     ```
   - Reiniciar el backend Flask. La aplicación volverá a operar contra MySQL sin afectación.

2. **Restauración de Respaldo MySQL (en caso de contingencia extrema):**
   - Respaldo SQL completo disponible en:
     `backend_flask/database_migration/backups/backup_plomapp_20260909_125027.sql`
   - Comando de restauración:
     ```bash
     "C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin\\mysql.exe" -u root -p plomapp < backend_flask/database_migration/backups/backup_plomapp_20260909_125027.sql
     ```
   - Respaldo JSON independiente de motor disponible en:
     `backend_flask/database_migration/backups/backup_plomapp_20260909_125027.json`
"""

with open(PLAN_FILE, "w", encoding="utf-8") as fp:
    fp.write(plan_content)

print(f"Plan de migración escrito exitosamente en: {PLAN_FILE}")
