import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

BACKEND_DIR = r"C:\Users\Anrid\plomaap_react_estable\backend_flask"
MIGRATION_DIR = os.path.join(BACKEND_DIR, "database_migration")
SCRIPT_PATH = os.path.join(MIGRATION_DIR, "migrate_to_postgres.py")

script_content = '''#!/usr/bin/env python
"""
PlomApp - Safe Migration from MySQL Backup to PostgreSQL 17.5
============================================================
Non-destructive:
- Reads from backup JSON (or MySQL in read-only mode).
- Does NOT touch or modify MySQL.
- Creates 'plomapp' database and schemas 'public' (modern) and 'legacy' (historic).
- Inserts existing 139 records preserving IDs.
- Synchronizes GENERATED BY DEFAULT AS IDENTITY sequences.
- Performs controlled INSERT tests to verify next ID generation.
- Validates PKs, FKs, Indexes, and Bcrypt hashes.
"""

import os
import sys
import json
import datetime
from decimal import Decimal
import psycopg2
from psycopg2 import sql
from psycopg2.extras import execute_batch, RealDictCursor

sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BACKUP_DIR = os.path.join(os.path.dirname(__file__), "backups")

# Find latest JSON backup
json_backups = sorted([f for f in os.listdir(BACKUP_DIR) if f.endswith(".json")])
if not json_backups:
    print("ERROR: No se encontró ningún backup JSON en", BACKUP_DIR)
    sys.exit(1)

BACKUP_FILE = os.path.join(BACKUP_DIR, json_backups[-1])
print(f"[*] Usando archivo de respaldo: {os.path.basename(BACKUP_FILE)}")

with open(BACKUP_FILE, encoding="utf-8") as fp:
    backup_data = json.load(fp)

# PostgreSQL Connection settings
PG_HOST = os.getenv("PGHOST", "localhost")
PG_PORT = int(os.getenv("PGPORT", 5432))
PG_USER = os.getenv("PGUSER", "postgres")
PG_PASS = os.getenv("PGPASSWORD", None)

if not PG_PASS:
    print("ERROR: La variable de entorno PGPASSWORD no está definida.")
    print("Por favor proporcione la contraseña de PostgreSQL para continuar.")
    sys.exit(1)

# Step 1: Connect to maintenance db (postgres) to create plomapp if not exists
print(f"[*] Conectando a PostgreSQL en {PG_HOST}:{PG_PORT} como '{PG_USER}'...")
try:
    conn_maint = psycopg2.connect(
        host=PG_HOST,
        port=PG_PORT,
        user=PG_USER,
        password=PG_PASS,
        dbname="postgres"
    )
    conn_maint.autocommit = True
    with conn_maint.cursor() as cur:
        cur.execute("SELECT 1 FROM pg_database WHERE datname = 'plomapp';")
        if not cur.fetchone():
            print("[+] Creando base de datos 'plomapp'...")
            cur.execute("CREATE DATABASE plomapp ENCODING 'UTF8';")
        else:
            print("[OK] Base de datos 'plomapp' ya existe.")
    conn_maint.close()
except Exception as e:
    print(f"ERROR conectando a PostgreSQL o creando la base de datos: {e}")
    sys.exit(1)

# Step 2: Connect to plomapp database
print("[*] Conectando a base de datos 'plomapp'...")
conn = psycopg2.connect(
    host=PG_HOST,
    port=PG_PORT,
    user=PG_USER,
    password=PG_PASS,
    dbname="plomapp"
)
conn.autocommit = False

try:
    with conn.cursor() as cur:
        # Step 3: Create Schemas
        print("[*] Creando esquemas 'public' y 'legacy'...")
        cur.execute("CREATE SCHEMA IF NOT EXISTS public;")
        cur.execute("CREATE SCHEMA IF NOT EXISTS legacy;")
        
        # Step 4: Create Modern Tables in public
        print("[*] Creando 8 tablas modernas en esquema 'public'...")
        
        # 1. services
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.services (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL,
            category VARCHAR(100),
            icon VARCHAR(255),
            color VARCHAR(7),
            base_price NUMERIC(10, 2) NOT NULL,
            description TEXT,
            duration_minutes INTEGER DEFAULT 60
        );
        """)

        # 2. users
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL,
            email VARCHAR(120) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            phone VARCHAR(20),
            address VARCHAR(255),
            avatar VARCHAR(255),
            role VARCHAR(20) NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'technician', 'admin')),
            status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
            email_verified BOOLEAN DEFAULT FALSE,
            reset_token VARCHAR(255),
            reset_token_expiry TIMESTAMP WITHOUT TIME ZONE,
            verification_token VARCHAR(255),
            verification_token_expiry TIMESTAMP WITHOUT TIME ZONE,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
        """)

        # 3. technician_profiles
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.technician_profiles (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
            specialties JSONB DEFAULT '[]'::jsonb,
            rating REAL DEFAULT 0.0,
            bio TEXT,
            schedule JSONB DEFAULT '{}'::jsonb,
            available BOOLEAN DEFAULT TRUE
        );
        CREATE UNIQUE INDEX IF NOT EXISTS idx_tech_user_id ON public.technician_profiles(user_id);
        """)

        # 4. user_addresses
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.user_addresses (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            label VARCHAR(100) NOT NULL,
            address VARCHAR(255) NOT NULL,
            latitude NUMERIC(10, 8),
            longitude NUMERIC(11, 8),
            place_id VARCHAR(255),
            reference VARCHAR(255),
            is_default BOOLEAN DEFAULT FALSE NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_user_addresses_user ON public.user_addresses(user_id);
        """)

        # 5. user_favorites
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.user_favorites (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            service_id INTEGER NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_user_service UNIQUE (user_id, service_id)
        );
        CREATE INDEX IF NOT EXISTS idx_user_favorites_user ON public.user_favorites(user_id);
        """)

        # 6. appointments
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.appointments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES public.users(id),
            technician_id INTEGER REFERENCES public.users(id),
            service_id INTEGER NOT NULL REFERENCES public.services(id),
            date DATE NOT NULL,
            time VARCHAR(5) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'scheduled', 'in_progress', 'completed', 'cancelled')),
            address VARCHAR(255),
            address_reference VARCHAR(255),
            user_address_id INTEGER REFERENCES public.user_addresses(id),
            notes TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_user_date ON public.appointments(user_id, date);
        CREATE INDEX IF NOT EXISTS idx_technician_date ON public.appointments(technician_id, date);
        CREATE INDEX IF NOT EXISTS idx_appointments_service ON public.appointments(service_id);
        """)

        # 7. devices
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.devices (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            user_agent VARCHAR(500),
            registered_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            last_access TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        """)

        # 8. webauthn_credentials
        cur.execute("""
        CREATE TABLE IF NOT EXISTS public.webauthn_credentials (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            credential_id VARCHAR(500) NOT NULL UNIQUE,
            public_key TEXT NOT NULL,
            sign_count INTEGER DEFAULT 0 NOT NULL,
            transports JSONB DEFAULT '[]'::jsonb,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE UNIQUE INDEX IF NOT EXISTS idx_webauthn_cred_id ON public.webauthn_credentials(credential_id);
        CREATE INDEX IF NOT EXISTS idx_webauthn_user ON public.webauthn_credentials(user_id);
        """)

        # Step 5: Create Legacy Tables in legacy
        print("[*] Creando 11 tablas históricas en esquema 'legacy'...")
        cur.execute("""
        CREATE TABLE IF NOT EXISTS legacy.usuarios (
            usuario_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            correo VARCHAR(100) NOT NULL UNIQUE,
            contrasena VARCHAR(255) NOT NULL,
            rol VARCHAR(20) NOT NULL,
            estado VARCHAR(20) NOT NULL,
            fecha_creacion TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS legacy.perfiles (
            usuario_id INTEGER PRIMARY KEY REFERENCES legacy.usuarios(usuario_id) ON DELETE CASCADE,
            nombre_completo VARCHAR(150),
            telefono VARCHAR(20),
            direccion_texto TEXT,
            latitud NUMERIC(10, 8),
            longitud NUMERIC(11, 8)
        );

        CREATE TABLE IF NOT EXISTS legacy.solicitudes_servicio (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cliente_id INTEGER REFERENCES legacy.usuarios(usuario_id),
            tecnico_id INTEGER REFERENCES legacy.usuarios(usuario_id),
            descripcion_inicial TEXT,
            estado VARCHAR(30),
            valor_visita_fijo NUMERIC(12, 2),
            creado_en TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS legacy.agendar_servicio (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            solicitud_id INTEGER REFERENCES legacy.solicitudes_servicio(id) ON DELETE CASCADE,
            dias_estimados_trabajo INTEGER,
            fecha_inicio_propuesta DATE,
            hora_inicio TIME,
            hora_fin TIME,
            comentarios_cliente_agenda TEXT,
            estado_agenda VARCHAR(30)
        );

        CREATE TABLE IF NOT EXISTS legacy.cotizaciones (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            solicitud_id INTEGER REFERENCES legacy.solicitudes_servicio(id) ON DELETE CASCADE,
            costo_transporte NUMERIC(12, 2),
            total_materiales_ia NUMERIC(12, 2),
            monto_total_proyecto NUMERIC(12, 2),
            anticipo_calculado NUMERIC(12, 2),
            proveedor_materiales VARCHAR(50),
            enviado_whatsapp BOOLEAN DEFAULT FALSE,
            enviado_email BOOLEAN DEFAULT FALSE,
            aceptada_por_cliente BOOLEAN DEFAULT FALSE
        );

        CREATE TABLE IF NOT EXISTS legacy.materiales_cotizacion (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cotizacion_id INTEGER REFERENCES legacy.cotizaciones(id) ON DELETE CASCADE,
            nombre_material VARCHAR(150),
            precio_promedio_ia NUMERIC(12, 2)
        );

        CREATE TABLE IF NOT EXISTS legacy.diagnosticos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            solicitud_id INTEGER REFERENCES legacy.solicitudes_servicio(id) ON DELETE CASCADE,
            foto_antes_url VARCHAR(255),
            especificaciones_tecnico TEXT,
            ia_render_url VARCHAR(255),
            mano_de_obra_estimada NUMERIC(12, 2)
        );

        CREATE TABLE IF NOT EXISTS legacy.garantias (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            solicitud_id INTEGER REFERENCES legacy.solicitudes_servicio(id) ON DELETE CASCADE,
            fecha_expiracion DATE,
            estado_garantia VARCHAR(30)
        );

        CREATE TABLE IF NOT EXISTS legacy.pagos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            solicitud_id INTEGER REFERENCES legacy.solicitudes_servicio(id) ON DELETE CASCADE,
            tipo_pago VARCHAR(30),
            monto NUMERIC(12, 2),
            payu_ref_pol VARCHAR(100),
            estado_pago VARCHAR(30),
            fecha_pago TIMESTAMP WITHOUT TIME ZONE
        );

        CREATE TABLE IF NOT EXISTS legacy.registros_chat (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            solicitud_id INTEGER REFERENCES legacy.solicitudes_servicio(id) ON DELETE CASCADE,
            emisor_id INTEGER REFERENCES legacy.usuarios(usuario_id),
            mensaje TEXT,
            archivo_url VARCHAR(255),
            es_texto_plano BOOLEAN DEFAULT TRUE,
            enviado_en TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS legacy.resenas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            solicitud_id INTEGER REFERENCES legacy.solicitudes_servicio(id) ON DELETE CASCADE,
            puntuacion SMALLINT,
            comentario TEXT
        );
        """)

        # Helper function for data insertion
        def insert_table_data(schema_name, table_name, rows):
            if not rows:
                return 0
            cols = list(rows[0].keys())
            col_identifiers = [sql.Identifier(c) for c in cols]
            table_ident = sql.Identifier(schema_name, table_name)
            
            # Format rows
            formatted_rows = []
            for r in rows:
                row_vals = []
                for k, v in r.items():
                    # Booleans
                    if k in ["email_verified", "available", "is_default", "enviado_whatsapp", "enviado_email", "aceptada_por_cliente", "es_texto_plano"]:
                        row_vals.append(bool(v) if v is not None else False)
                    # JSON fields
                    elif k in ["specialties", "schedule", "transports"]:
                        if v is None:
                            row_vals.append(None)
                        elif isinstance(v, (list, dict)):
                            row_vals.append(json.dumps(v))
                        else:
                            row_vals.append(str(v))
                    else:
                        row_vals.append(v)
                formatted_rows.append(row_vals)

            placeholders = sql.SQL(', ').join(sql.Placeholder() * len(cols))
            insert_query = sql.SQL("INSERT INTO {table} ({cols}) OVERRIDING SYSTEM VALUE VALUES ({vals}) ON CONFLICT DO NOTHING").format(
                table=table_ident,
                cols=sql.SQL(', ').join(col_identifiers),
                vals=placeholders
            )
            execute_batch(cur, insert_query, formatted_rows)
            return len(rows)

        # Step 6: Insert Data in Topological Order
        print("\n[*] Insertando registros en esquema 'public' (orden topológico)...")
        # 1. services
        c1 = insert_table_data("public", "services", backup_data["tables"].get("services", {}).get("rows", []))
        print(f"  - public.services: {c1} filas")
        
        # 2. users
        c2 = insert_table_data("public", "users", backup_data["tables"].get("users", {}).get("rows", []))
        print(f"  - public.users: {c2} filas")
        
        # 3. technician_profiles
        c3 = insert_table_data("public", "technician_profiles", backup_data["tables"].get("technician_profiles", {}).get("rows", []))
        print(f"  - public.technician_profiles: {c3} filas")
        
        # 4. user_addresses
        c4 = insert_table_data("public", "user_addresses", backup_data["tables"].get("user_addresses", {}).get("rows", []))
        print(f"  - public.user_addresses: {c4} filas")
        
        # 5. user_favorites
        c5 = insert_table_data("public", "user_favorites", backup_data["tables"].get("user_favorites", {}).get("rows", []))
        print(f"  - public.user_favorites: {c5} filas")
        
        # 6. appointments
        c6 = insert_table_data("public", "appointments", backup_data["tables"].get("appointments", {}).get("rows", []))
        print(f"  - public.appointments: {c6} filas")
        
        # 7. devices
        c7 = insert_table_data("public", "devices", backup_data["tables"].get("devices", {}).get("rows", []))
        print(f"  - public.devices: {c7} filas")
        
        # 8. webauthn_credentials
        c8 = insert_table_data("public", "webauthn_credentials", backup_data["tables"].get("webauthn_credentials", {}).get("rows", []))
        print(f"  - public.webauthn_credentials: {c8} filas")

        print("\n[*] Insertando registros en esquema 'legacy'...")
        legacy_tables = [
            "usuarios", "perfiles", "solicitudes_servicio", "cotizaciones",
            "diagnosticos", "garantias", "pagos", "registros_chat",
            "resenas", "agendar_servicio", "materiales_cotizacion"
        ]
        for lt in legacy_tables:
            c = insert_table_data("legacy", lt, backup_data["tables"].get(lt, {}).get("rows", []))
            print(f"  - legacy.{lt}: {c} filas")

        # Step 7: Synchronize Sequences explicitly for GENERATED BY DEFAULT AS IDENTITY
        print("\n[*] Sincronizando secuencias de identidad...")
        all_tables_to_sync = [
            ("public", "services", "id"),
            ("public", "users", "id"),
            ("public", "technician_profiles", "id"),
            ("public", "user_addresses", "id"),
            ("public", "user_favorites", "id"),
            ("public", "appointments", "id"),
            ("public", "devices", "id"),
            ("public", "webauthn_credentials", "id"),
            ("legacy", "usuarios", "usuario_id"),
            ("legacy", "solicitudes_servicio", "id"),
            ("legacy", "agendar_servicio", "id"),
            ("legacy", "cotizaciones", "id"),
            ("legacy", "materiales_cotizacion", "id"),
            ("legacy", "diagnosticos", "id"),
            ("legacy", "garantias", "id"),
            ("legacy", "pagos", "id"),
            ("legacy", "registros_chat", "id"),
            ("legacy", "resenas", "id")
        ]

        for s_name, t_name, id_col in all_tables_to_sync:
            # Query sequence linked to identity column
            cur.execute(f"SELECT pg_get_serial_sequence('{s_name}.{t_name}', '{id_col}');")
            seq_res = cur.fetchone()
            seq_name = seq_res[0] if seq_res else None
            
            cur.execute(f"SELECT COALESCE(MAX({id_col}), 0) FROM {s_name}.{t_name};")
            max_id = cur.fetchone()[0]
            next_id = max_id + 1 if max_id > 0 else 1

            if seq_name:
                cur.execute(f"SELECT setval('{seq_name}', {max(max_id, 1)}, {max_id > 0});")
                print(f"  [OK] Secuencia {seq_name} sincronizada (MAX ID: {max_id}, próximo: {next_id})")
            else:
                cur.execute(f"ALTER TABLE {s_name}.{t_name} ALTER COLUMN {id_col} RESTART WITH {next_id};")
                print(f"  [OK] Identidad {s_name}.{t_name}.{id_col} reiniciada en {next_id}")

        # Step 8: Controlled INSERT test to verify next ID generation without collisions
        print("\n[*] Ejecutando prueba controlada de INSERT para verificar autoincremento...")
        cur.execute("""
        INSERT INTO public.users (name, email, password_hash, role, status)
        VALUES ('Test Identity Verification', 'test_identity_check@plomaap.com', 'test_hash', 'customer', 'inactive')
        RETURNING id;
        """)
        new_test_id = cur.fetchone()[0]
        expected_next = 15 # users had 14 records
        print(f"  [+] Inserción de prueba en public.users exitosa. ID asignado: {new_test_id} (esperado: {expected_next})")
        assert new_test_id >= expected_next, f"Conflicto de ID: {new_test_id} < {expected_next}"
        
        # Clean up test record immediately
        cur.execute("DELETE FROM public.users WHERE id = %s;", (new_test_id,))
        # Reset sequence back to 14
        cur.execute("SELECT setval(pg_get_serial_sequence('public.users', 'id'), 14, true);")
        print("  [OK] Registro de prueba eliminado y secuencia restaurada correctamente.")

    conn.commit()
    print("\n" + "=" * 60)
    print("MIGRACIÓN A POSTGRESQL COMPLETADA EXITOSAMENTE")
    print("=" * 60)

except Exception as e:
    conn.rollback()
    print(f"\n[!] ERROR DURANTE LA MIGRACIÓN (ROLLBACK EJECUTADO): {e}")
    sys.exit(1)
finally:
    conn.close()
'''

with open(SCRIPT_PATH, "w", encoding="utf-8") as fp:
    fp.write(script_content)

print(f"Script de migración escrito en: {SCRIPT_PATH}")
